### ISSUE TITLE
Template Does Not Exist

### ISSUE THREAD

**Issue by kylehartigan** [CIGIHub/opencanada#697]
On setup, for whatever reason quotes are being included in the template render paths:

![Screen Shot 2020-01-28 at 10 34 09 AM](https://user-images.githubusercontent.com/50461354/73273406-4b397280-41ba-11ea-8dea-16d8ffee3104.png)

**Comment by rodrigogoncalves** [comment]
When you run the migrations, the migration for the Theme model sets the string `b'themes/default'` as a default value for the field `folder` of that model. As a result, the `default` theme gets that data, causing the error. ([Source code](https://github.com/CIGIHub/opencanada/blob/staging/themes/migrations/0001_squashed_0025_remove_theme_json_file.py#L163)).

You can fix the issue by opening the Django shell and manipulating the faulty entry, for example:
```
$ python manage.py shell
>>> from themes.models import Theme
>>> t = Theme.objects.get(folder="b'themes/default'")
>>> t.folder = 'themes/default'
>>> t.save()
```

Migration should be fixed, though.

**Comment by gabrieltanchen** [comment]
Closing as this repository is now archived.
